# Generated by Django 5.1.4 on 2024-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='summarized_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='article_doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
