# Generated by Django 5.1.4 on 2025-01-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0007_remove_usermessage_user_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
