# Generated by Django 5.1.4 on 2024-12-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
