# Generated by Django 5.1.4 on 2025-01-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_api', '0002_remove_article_authors_remove_article_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
