# Generated by Django 5.1.4 on 2025-01-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_api', '0003_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
