# Generated by Django 5.1.4 on 2025-01-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_api', '0005_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
